# ===============================
# DATABASE CONFIG - AIVEN CLOUD
# ===============================

spring.datasource.url=jdbc:mysql://mysql-26eded0d-centropsico.i.aivencloud.com:13965/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# ===============================
# FILE UPLOAD
# ===============================

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=3MB


# ===============================
# ERROR CONFIG
# ===============================

server.error.whitelabel.enabled=false
server.error.path=/error


# ===============================
# EMAIL CONFIG - MAILPRO SMTP
# ===============================

spring.mail.host=smtp.mailpro.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=20000
spring.mail.properties.mail.smtp.timeout=20000
spring.mail.properties.mail.smtp.writetimeout=20000

app.mail.from=${MAIL_FROM}